// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyBackend.Data;

#nullable disable

namespace SurveyBackend.Data.Migrations;

[DbContext(typeof(MainDbContext))]
[Migration("20261004175807_EnforceStringLengths")]
partial class EnforceStringLengths
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

        modelBuilder.Entity("SurveyBackend.Models.Questionnaire", b =>
            {
                b.Property<string>("QuestionnaireId")
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("LLMPageNames")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("TEXT");

                b.Property<string>("SurveyId")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("SurveyJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("QuestionnaireId");

                b.HasIndex("SurveyId");

                b.ToTable("questionnaires", null, t =>
                    {
                        t.HasCheckConstraint("CK_questionnaires_QuestionnaireId_Length", "length(\"QuestionnaireId\") <= 8");

                        t.HasCheckConstraint("CK_questionnaires_SurveyId_Length", "length(\"SurveyId\") <= 8");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.Request", b =>
            {
                b.Property<string>("RequestId")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDisabled")
                    .HasColumnType("INTEGER");

                b.Property<int>("RequestType")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.HasKey("RequestId");

                b.HasIndex("UserId");

                b.ToTable("requests", null, t =>
                    {
                        t.HasCheckConstraint("CK_requests_RequestId_Length", "length(\"RequestId\") <= 16");

                        t.HasCheckConstraint("CK_requests_UserId_Length", "length(\"UserId\") <= 16");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.ReviewSubmissionData", b =>
            {
                b.Property<string>("ReviewSubmissionDataId")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("AIInsights")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("SubmissionId")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.HasKey("ReviewSubmissionDataId");

                b.HasIndex("SubmissionId");

                b.ToTable("review_submissions", null, t =>
                    {
                        t.HasCheckConstraint("CK_review_submissions_ReviewSubmissionDataId_Length", "length(\"ReviewSubmissionDataId\") <= 16");

                        t.HasCheckConstraint("CK_review_submissions_SubmissionId_Length", "length(\"SubmissionId\") <= 16");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.ReviewVote", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ReviewSubmissionDataId")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<DateTime>("VoteTime")
                    .HasColumnType("TEXT");

                b.Property<int>("VoteType")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ReviewSubmissionDataId");

                b.HasIndex("UserId");

                b.ToTable("review_votes", null, t =>
                    {
                        t.HasCheckConstraint("CK_review_votes_ReviewSubmissionDataId_Length", "length(\"ReviewSubmissionDataId\") <= 16");

                        t.HasCheckConstraint("CK_review_votes_UserId_Length", "length(\"UserId\") <= 16");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.Submission", b =>
            {
                b.Property<string>("SubmissionId")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDisabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("QuestionnaireId")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("SurveyData")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.HasKey("SubmissionId");

                b.HasIndex("QuestionnaireId");

                b.HasIndex("UserId");

                b.ToTable("submissions", null, t =>
                    {
                        t.HasCheckConstraint("CK_submissions_QuestionnaireId_Length", "length(\"QuestionnaireId\") <= 8");

                        t.HasCheckConstraint("CK_submissions_SubmissionId_Length", "length(\"SubmissionId\") <= 16");

                        t.HasCheckConstraint("CK_submissions_UserId_Length", "length(\"UserId\") <= 16");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.Survey", b =>
            {
                b.Property<string>("SurveyId")
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsVerifySurvey")
                    .HasColumnType("INTEGER");

                b.Property<bool>("NeedReview")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<bool>("UniquePerUser")
                    .HasColumnType("INTEGER");

                b.HasKey("SurveyId");

                b.ToTable("surveys", null, t =>
                    {
                        t.HasCheckConstraint("CK_surveys_Description_Length", "length(\"Description\") <= 1000");

                        t.HasCheckConstraint("CK_surveys_SurveyId_Length", "length(\"SurveyId\") <= 8");

                        t.HasCheckConstraint("CK_surveys_Title_Length", "length(\"Title\") <= 200");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.User", b =>
            {
                b.Property<string>("UserId")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("QQId")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<int>("UserGroup")
                    .HasColumnType("INTEGER");

                b.HasKey("UserId");

                b.HasIndex("QQId")
                    .IsUnique();

                b.ToTable("users", null, t =>
                    {
                        t.HasCheckConstraint("CK_users_QQId_Length", "length(\"QQId\") <= 16");

                        t.HasCheckConstraint("CK_users_UserId_Length", "length(\"UserId\") <= 16");
                    });
            });

        modelBuilder.Entity("SurveyBackend.Models.Questionnaire", b =>
            {
                b.HasOne("SurveyBackend.Models.Survey", "Survey")
                    .WithMany()
                    .HasForeignKey("SurveyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Survey");
            });

        modelBuilder.Entity("SurveyBackend.Models.Request", b =>
            {
                b.HasOne("SurveyBackend.Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("SurveyBackend.Models.ReviewSubmissionData", b =>
            {
                b.HasOne("SurveyBackend.Models.Submission", "Submission")
                    .WithMany()
                    .HasForeignKey("SubmissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Submission");
            });

        modelBuilder.Entity("SurveyBackend.Models.ReviewVote", b =>
            {
                b.HasOne("SurveyBackend.Models.ReviewSubmissionData", "ReviewSubmissionData")
                    .WithMany()
                    .HasForeignKey("ReviewSubmissionDataId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SurveyBackend.Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ReviewSubmissionData");

                b.Navigation("User");
            });

        modelBuilder.Entity("SurveyBackend.Models.Submission", b =>
            {
                b.HasOne("SurveyBackend.Models.Questionnaire", "Questionnaire")
                    .WithMany()
                    .HasForeignKey("QuestionnaireId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SurveyBackend.Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Questionnaire");

                b.Navigation("User");
            });
#pragma warning restore 612, 618
    }
}
