@SurveyBackend_HostAddress = https://localhost:7224


POST {{SurveyBackend_HostAddress}}/survey/checkUserId
Content-Type: application/json

"qwq"

###

GET {{SurveyBackend_HostAddress}}/survey/getSurvey

###
