@SurveyBackend_HostAddress = https://localhost:7224


POST {{SurveyBackend_HostAddress}}/survey/checkUserId
Content-Type: application/json

"qwq"

###

GET {{SurveyBackend_HostAddress}}/survey/getSurvey

###

POST {{SurveyBackend_HostAddress}}/survey/submitSurvey
Content-Type: application/json

{
  "userId": "qwq",
  "Answers": "{\"1\": \"A\", \"2\": \"B\", \"3\": \"C\", \"4\": \"D\", \"5\": \"E\"}"
}

###
