// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyBackend.Models;

#nullable disable

namespace SurveyBackend.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260215210633_SetCascadeDeleteBehavior")]
    partial class SetCascadeDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SurveyBackend.Models.Questionnaire", b =>
                {
                    b.Property<string>("QuestionnaireId")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("LLMPageNames")
                        .HasColumnType("json");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("SurveyJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("QuestionnaireId");

                    b.HasIndex("SurveyId");

                    b.ToTable("questionnaires", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.Request", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.ReviewSubmissionData", b =>
                {
                    b.Property<string>("ReviewSubmissionDataId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("AIInsights")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ReviewSubmissionDataId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("review_submissions", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.ReviewVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ReviewSubmissionDataId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("VoteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VoteType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewSubmissionDataId");

                    b.HasIndex("UserId");

                    b.ToTable("review_votes", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.Submission", b =>
                {
                    b.Property<string>("SubmissionId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QuestionnaireId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("SurveyData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("SubmissionId");

                    b.HasIndex("QuestionnaireId");

                    b.HasIndex("UserId");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.Survey", b =>
                {
                    b.Property<string>("SurveyId")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsVerifySurvey")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NeedReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("UniquePerUser")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SurveyId");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("QQId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("UserGroup")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("QQId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SurveyBackend.Models.Questionnaire", b =>
                {
                    b.HasOne("SurveyBackend.Models.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyBackend.Models.Request", b =>
                {
                    b.HasOne("SurveyBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurveyBackend.Models.ReviewSubmissionData", b =>
                {
                    b.HasOne("SurveyBackend.Models.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SurveyBackend.Models.ReviewVote", b =>
                {
                    b.HasOne("SurveyBackend.Models.ReviewSubmissionData", "ReviewSubmissionData")
                        .WithMany()
                        .HasForeignKey("ReviewSubmissionDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewSubmissionData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurveyBackend.Models.Submission", b =>
                {
                    b.HasOne("SurveyBackend.Models.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
